export interface Pedal {
  id: string;
  brand: string;
  model: string;
  category: "overdrive" | "distortion" | "delay" | "reverb" | "modulation" | "fuzz" | "compressor" | "eq" | "wah" | "tuner" | "looper" | "other";
  width: number;
  height: number;
  imageUrl: string;
  color: string;
}

export const pedals: Pedal[] = [
  {
    id: "boss-ds1",
    brand: "Boss",
    model: "DS-1 Distortion",
    category: "distortion",
    width: 73,
    height: 129,
    imageUrl: "https://images.equipboard.com/uploads/item/image/16661/boss-ds-1-distortion-xl.jpg?v=1734076645",
    color: "#f97316",
  },
  {
    id: "boss-bd2",
    brand: "Boss",
    model: "BD-2 Blues Driver",
    category: "overdrive",
    width: 73,
    height: 129,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4426/boss-bd-2-blues-driver-xl.jpg?v=1734123609",
    color: "#3b82f6",
  },
  {
    id: "boss-dd3",
    brand: "Boss",
    model: "DD-3 Digital Delay",
    category: "delay",
    width: 73,
    height: 129,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4487/boss-dd-3-digital-delay-xl.jpg?v=1734126346",
    color: "#60a5fa",
  },
  {
    id: "boss-rv6",
    brand: "Boss",
    model: "RV-6 Reverb",
    category: "reverb",
    width: 73,
    height: 129,
    imageUrl: "https://images.equipboard.com/uploads/item/image/10849/boss-rv-6-xl.jpg?v=1734020803",
    color: "#a855f7",
  },
  {
    id: "boss-tu3",
    brand: "Boss",
    model: "TU-3 Chromatic Tuner",
    category: "tuner",
    width: 73,
    height: 129,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4401/boss-tu-3-chromatic-tuner-xl.jpg?v=1734124296",
    color: "#000000",
  },
  {
    id: "boss-ce2w",
    brand: "Boss",
    model: "CE-2W Chorus",
    category: "modulation",
    width: 73,
    height: 129,
    imageUrl: "https://images.equipboard.com/uploads/item/image/10776/boss-ce-2w-waza-craft-chorus-xl.jpg?v=1734021426",
    color: "#ec4899",
  },
  {
    id: "ibanez-ts9",
    brand: "Ibanez",
    model: "TS9 Tube Screamer",
    category: "overdrive",
    width: 74,
    height: 127,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4391/ibanez-ts9-tube-screamer-xl.jpg?v=1734124386",
    color: "#22c55e",
  },
  {
    id: "ehx-bigmuff",
    brand: "Electro-Harmonix",
    model: "Big Muff Pi",
    category: "fuzz",
    width: 89,
    height: 165,
    imageUrl: "https://images.equipboard.com/uploads/item/image/5163/electro-harmonix-big-muff-pi-xl.jpg?v=1733982817",
    color: "#ef4444",
  },
  {
    id: "mxr-dynacomp",
    brand: "MXR",
    model: "Dyna Comp",
    category: "compressor",
    width: 64,
    height: 114,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4396/mxr-dyna-comp-xl.jpg?v=1734124343",
    color: "#dc2626",
  },
  {
    id: "mxr-phase90",
    brand: "MXR",
    model: "Phase 90",
    category: "modulation",
    width: 64,
    height: 114,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4464/mxr-phase-90-xl.jpg?v=1734125867",
    color: "#f97316",
  },
  {
    id: "tc-flashback",
    brand: "TC Electronic",
    model: "Flashback Delay",
    category: "delay",
    width: 71,
    height: 124,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4509/tc-electronic-flashback-delay-xl.jpg?v=1734125352",
    color: "#0ea5e9",
  },
  {
    id: "tc-hall-of-fame",
    brand: "TC Electronic",
    model: "Hall of Fame Reverb",
    category: "reverb",
    width: 71,
    height: 124,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4510/tc-electronic-hall-of-fame-reverb-xl.jpg?v=1734125341",
    color: "#8b5cf6",
  },
  {
    id: "strymon-timeline",
    brand: "Strymon",
    model: "Timeline",
    category: "delay",
    width: 178,
    height: 133,
    imageUrl: "https://images.equipboard.com/uploads/item/image/7665/strymon-timeline-xl.jpg?v=1734000665",
    color: "#1e40af",
  },
  {
    id: "strymon-bigsky",
    brand: "Strymon",
    model: "BigSky",
    category: "reverb",
    width: 178,
    height: 133,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4546/strymon-bigsky-xl.jpg?v=1734105802",
    color: "#06b6d4",
  },
  {
    id: "jhs-morning-glory",
    brand: "JHS",
    model: "Morning Glory",
    category: "overdrive",
    width: 64,
    height: 114,
    imageUrl: "https://images.equipboard.com/uploads/item/image/5190/jhs-morning-glory-v4-xl.jpg?v=1733981906",
    color: "#fcd34d",
  },
  {
    id: "klon-centaur",
    brand: "Klon",
    model: "Centaur",
    category: "overdrive",
    width: 140,
    height: 89,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4389/klon-centaur-xl.jpg?v=1734124405",
    color: "#d4a574",
  },
  {
    id: "proco-rat2",
    brand: "Pro Co",
    model: "RAT2",
    category: "distortion",
    width: 89,
    height: 114,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4394/proco-rat-2-xl.jpg?v=1734124367",
    color: "#000000",
  },
  {
    id: "walrus-julia",
    brand: "Walrus Audio",
    model: "Julia Chorus",
    category: "modulation",
    width: 76,
    height: 127,
    imageUrl: "https://images.equipboard.com/uploads/item/image/15158/walrus-audio-julia-xl.jpg?v=1734093406",
    color: "#7dd3fc",
  },
  {
    id: "zvex-fuzz-factory",
    brand: "ZVEX",
    model: "Fuzz Factory",
    category: "fuzz",
    width: 64,
    height: 89,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4374/z-vex-fuzz-factory-xl.jpg?v=1734126071",
    color: "#8b5cf6",
  },
  {
    id: "dunlop-crybaby",
    brand: "Dunlop",
    model: "Cry Baby Wah",
    category: "wah",
    width: 102,
    height: 254,
    imageUrl: "https://images.equipboard.com/uploads/item/image/4457/dunlop-gcb95-cry-baby-wah-xl.jpg?v=1734125972",
    color: "#374151",
  },
];

export function getPedalById(id: string): Pedal | undefined {
  return pedals.find((p) => p.id === id);
}

export function getPedalsByCategory(category: Pedal["category"]): Pedal[] {
  return pedals.filter((p) => p.category === category);
}

export const categories: { value: Pedal["category"]; label: string }[] = [
  { value: "overdrive", label: "Overdrive" },
  { value: "distortion", label: "Distortion" },
  { value: "fuzz", label: "Fuzz" },
  { value: "delay", label: "Delay" },
  { value: "reverb", label: "Reverb" },
  { value: "modulation", label: "Modulation" },
  { value: "compressor", label: "Compressor" },
  { value: "eq", label: "EQ" },
  { value: "wah", label: "Wah" },
  { value: "tuner", label: "Tuner" },
  { value: "looper", label: "Looper" },
  { value: "other", label: "Other" },
];
